### ISSUE TITLE
Helper function created where both parameters have the same name

### ISSUE THREAD

**Issue by Plukers** [krauthaufen/FShade#10]
FShade fragment shader code:
```fsharp
let (clippedVa, clippedVc) = clipPatch(patch)

let (clampedPoint, _, _, _) = clampPointToPolygon clippedVa clippedVc point t2l

let clampedPoint2d = 
    let cp = t2l * (clampedPoint- clippedVa.[0])
    V2d(cp.X, cp.Y)
```

When this is compiled, the following GLSL code is generated to compute `clampedPoint2d`:

```glsl
vec2 helper(tup_Aardvark_Base_Arrays_Arr2_N5_Aardvark_Base_V3d_int32 patternInput, mat3x3 t2l, tup_Aardvark_Base_V3d_int32_int32_int32 patternInput)
{
    vec3 cp = ((patternInput.Item0 - patternInput1.Item0[0]) * t2l);
    return vec2(cp.x, cp.y);
}

tup_Aardvark_Base_Arrays_Arr2_N5_Aardvark_Base_V3d_int32 patternInput = Render_EffectUtils_clipPatch_11MVozJCVzGFI0BA2ITmWQ(patch);

tup_Aardvark_Base_V3d_int32_int32_int32 patternInput1 = Render_EffectUtils_clampPointToPolygon_u3q3UoKGkBMzZDq5JTwd1Q(patternInput.Item0, patternInput.Item1, point, t2l);

vec2 clampedPoint2d = helper(patternInput, t2l, patternInput1);
```

The helper function has two parameters with the name `patternInput`, which leads to the error:
```
Message=[GL] surface compilation failed: Vertex:
    0(264) : error C1038: declaration of "patternInput" conflicts with previous declaration at 0(264)
```

**Comment by krauthaufen** [comment]
but these two variables are in entirely different scopes, aren't they?
GLSL variable scoping is super-weir obviously. I'll see if there's an easy fix but is suspect not.

Do you have a workaround?

**Comment by Plukers** [comment]
The scope structure is

```fsharp
let (clippedVa, clippedVc) = clipPatch(patch)

if conditionA then

    if conditionB then

        let (clampedPoint, _, _, _) = clampPointToPolygon clippedVa clippedVc point t2l

        let clampedPoint2d = 
            let cp = t2l * (clampedPoint- clippedVa.[0])
            V2d(cp.X, cp.Y)
```

A possible workaround could be:
```
let clampedPointProjected = (t2l * (clampedPoint- clippedVa.[0]))
let clampedPoint2d = V2d(clampedPointProjected .X, clampedPointProjected .Y)
```
I can imagine that this way the helper function will not be created. It is, however, not tested yet because when I write it this way my program freezes on startup. 
I will post an update after it works again and is tested.

**Comment by krauthaufen** [comment]
I finally managed to reproduce the issue and found a relatively easy fix for it.
Are you working with FShade `3.*.*` or `4.*.*` at the moment?

In case you're using FShade3 you can just clone it next to your project and use `build AddSource ..\FShade`...
If you're using `4.*.*` then you can use the package I'm just creating (4.0.1).

Let me know if that fixes your problem!
Cheers

**Comment by krauthaufen** [comment]
Follow up: when using AddSource you need to use the `v3` branch of FShade.
I backported the fix from master.

**Comment by krauthaufen** [comment]
should be fixed
