### ISSUE TITLE
Missing vector swizzles

### ISSUE THREAD

**Issue by luithefirst** [krauthaufen/FShade#25]
The support for vector swizzles is currently limited to permutations of 2 and 3 vector components. Missing are:
- permutations of 4 components (e.g. `WZXY` to reorder the Gather4 result)
- swizzles with constants (e.g. `XYO`)
- swizzles with duplicates (e.g `XXYY`)

**Comment by krauthaufen** [comment]
Not sure if these exist in GLSL, we could certainly simulate those but that raises the question of how we generally treat these things.

Arguably we already started "simulating" things with `lengthSquared`, etc so it should probably be fine to include those.

**Comment by krauthaufen** [comment]
turns out, this is not so easy to do...
consider `(a + b*c).XIY`: we'd have to rewrite that as `vec3((a+b*c).x, 1.0, (a+b*c).y)` which evaluates the expression twice...

So we'd need to do this rather early in the compiler and replace it with a let-binding before swizzling

**Comment by krauthaufen** [comment]
Okay I have a sketch for supporting that properly which produces code like this:

```glsl
vec2 tmp = ((3.0 * fs_thing) + vec2(1.0, 1.0));
ColorsOut = vec4(1.0, -1.0, tmp.x, tmp.y);
```

from the input

```fsharp
let test(v : Vertex) =
    fragment {
        return (3.0 * v.thing + V2d.II).PNXY
    }
```

**Comment by luithefirst** [comment]
Nice to see that you are already working on this!  Yes, the ones with constants cannot be directly translated to glsl. With you sketch it becomes clear what needs to be done and you see how convenient it gets with them :)

**Comment by krauthaufen** [comment]
All the. swizzles should be supported now. however the `I`, `O`, `P`, `N` things will only work for `int`, `float32` and `double` atm (don't know if there are any other relevant cases)

I will create a package once the other small issues have been addressed

**Comment by luithefirst** [comment]
Nice implementation, thanks! There is no hurry ;-)
