### ISSUE TITLE
Missing `step`

### ISSUE THREAD

**Issue by luithefirst** [krauthaufen/FShade#26]
I currently use a local helper to use this intrinsic function:
```
/// x < edge ? 0.0 : 1.0
[<GLSLIntrinsic("step({0},{1})"); Inline>] 
let step (edge : 'a) (x : 'a) : 'a = onlyInShaderCode "step"
```
It would be nice if this is also natively supported. We would also need to add this to Aardvark.Base.

**Comment by krauthaufen** [comment]
What does it do?

**Comment by luithefirst** [comment]
https://registry.khronos.org/OpenGL-Refpages/gl4/html/step.xhtml
short for: `if x < edge then 0.0 else 1.0`

**Comment by hyazinthh** [comment]
Added in the `v53` branch along with `linearstep`
