### ISSUE TITLE
bad swizzle: 'o'

### ISSUE THREAD

**Issue by luithefirst** [krauthaufen/FShade#29]
```
[<Test>]
let ``Foo``() =
    let input =
        <@
            fun (a : V3d) ->
                a.Normalized
        @>
    
    input |> Opt.run |> printfn "%A"
```

This test produces an exception with "bad swizzle: 'o'" in 5.2.12

**Comment by hyazinthh** [comment]
This is fixed in the `v53` branch, probably should be backported.

See: https://github.com/krauthaufen/FShade/commit/be533446383e659de2a9c3fc0a3325cbe8b217ea

**Comment by voronoipotato** [comment]
is there a reason someone wouldn't want to just upgrade?

**Comment by krauthaufen** [comment]
5.3 is still prerelease and contains several breaking changes. It might not be trivial to upgrade all dependent projects right away, so I think we should backport that.
