### ISSUE TITLE
M44d.TransformPosProj

### ISSUE THREAD

**Issue by luithefirst** [krauthaufen/FShade#30]
It might be convenient also translate M44d.TransformPosProj to an appropriate shader code (like we already do with TransformDir and other).

````
let p = uniform.ProjTrafo.TransformPosProj someVec3
````

**Comment by krauthaufen** [comment]
Isn't the implementation in your commit wrong? Or did i miss the w-division?

**Comment by hyazinthh** [comment]
Should be there. Maybe you looked at the `-Full`  variant in `Compiler.fs`? `TransformPosProj` is implemented at expression level in `Shader.fs`.

**Comment by krauthaufen** [comment]
But the full variant should also divide by w right?

**Comment by hyazinthh** [comment]
The `Aardvark.Base` implementation does not do the division.

**Comment by krauthaufen** [comment]
Okay, didn't know that, but `TransformPosProjFull` is then identical to `m * V4d(arg, 1.0)` right?

**Comment by hyazinthh** [comment]
Yeah, it's identical.

**Comment by luithefirst** [comment]
I also find the name misleading, it should only be `TransformPosFull`.
